FROM ruby:3.2.2

RUN mkdir /app
WORKDIR /app

RUN apt-get update -qq && \
    apt-get -y install build-essential wget git sqlite3 libsqlite3-dev

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock

ENV RAILS_ENV development

EXPOSE 3000

RUN bundle check || bundle install

COPY . ./

RUN ./bin/setup

ENTRYPOINT ["./entrypoint.sh"]
