require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/posts', type: :request do

  # Using fixtures defined here: spec/fixtures/posts.yml
  fixtures :posts

  describe 'GET /index' do
    it 'renders a successful response' do
      get posts_url, as: :json
      expect(response).to be_successful
    end
  end

  describe 'PUT /upvote' do
    let!(:my_post) { Fabricate :post, upvotes: 0, downvotes: 0 }

    it 'increments post upvotes by 1' do
      put post_upvote_url(my_post), as: :json
      my_post.reload
      expect(my_post.upvotes).to eq 1
      expect(my_post.downvotes).to eq 0
      expect(response).to be_successful
    end
  end

  describe 'PUT /downvote' do
  end
end
